local s,id=GetID()
function s.initial_effect(c)
	Gacha2.UnitCharacter(c)
	Gacha3.DuelAtkUnitCharacter(c)
	
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e1:SetCode(EVENT_BATTLE_START)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCountLimit(1)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(s.cbcon)
	e1:SetTarget(s.cbtg)
	e1:SetOperation(s.cbop)
	c:RegisterEffect(e1)
end
function s.cbcon(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetAttacker():IsControler(1-tp) and e:GetHandler():IsAttackPos() and Duel.GetAttackTarget()~=nil
	and Duel.GetAttackTarget()~=e:GetHandler()
end
function s.cbtg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
	Duel.SetChainLimit(aux.FALSE)
end
function s.cbop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
		local g=Duel.SelectMatchingCard(tp,Gacha2.btcounterfilter2,tp,LOCATION_ONFIELD,0,0,1,c)
		tc=g:GetFirst()
		if #g==0 then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetValue(0xa06)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e1) end
		if #g==1 then 	
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_ADD_SETCODE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetValue(0xa05)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(tc)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_ADD_SETCODE)
		e3:SetRange(LOCATION_ONFIELD)
		e3:SetValue(0xa05)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		tc:RegisterEffect(e3)
		Duel.ChangePosition(tc,POS_FACEUP_DEFENSE)
		local def=tc:GetDefense()
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_UPDATE_DEFENSE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetValue(def)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(tc)
		e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e5:SetCode(EVENT_LEAVE_FIELD)
		e5:SetRange(LOCATION_ONFIELD)
		e5:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e5:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e5:SetCondition(s.btcounterdescon2)
		e5:SetOperation(s.btcounterdesop2)
		tc:RegisterEffect(e5)	end
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_FIELD)
		e6:SetRange(LOCATION_ONFIELD)
		e6:SetCode(EFFECT_CHANGE_DAMAGE)
		e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e6:SetTargetRange(1,0)
		e6:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e6:SetValue(0)
		c:RegisterEffect(e6)
		local e7=Effect.CreateEffect(c)
		e7:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
		e7:SetCode(EVENT_PRE_DAMAGE_CALCULATE)
		e7:SetRange(LOCATION_ONFIELD)
		e7:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e7:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		e7:SetOperation(s.btcoutertgop)
		c:RegisterEffect(e7)
end
function s.btcounterdesfilter2(c)
	return c:IsReason(REASON_BATTLE)
end
function s.btcounterdescon2(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(s.btcounterdesfilter2,1,nil)
end
function s.btcounterdesop2(e,tp,eg,ep,ev,re,r,rp)
	Duel.Destroy(e:GetHandler(),REASON_BATTLE)
end
function s.btcoutertgop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.CalculateDamage(at,c)
end