local s,id=GetID()
function s.initial_effect(c)
	Gacha2.UnitCharacter(c)
	Gacha3.DuelAtkUnitCharacter(c)
	
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_SPSUMMON_SUCCESS)
	e1:SetOperation(s.activate)
	c:RegisterEffect(e1)
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local deck=Duel.GetMatchingGroup(nil,tp,LOCATION_DECK,0,nil)
	local refill=Duel.GetMatchingGroup(nil,tp,LOCATION_GRAVE,0,nil)
	if Duel.GetMatchingGroupCount(nil,tp,LOCATION_DECK,0,nil)<4 then
	Duel.SendtoGrave(deck,REASON_RULE)
	Duel.SendtoDeck(refill,nil,SEQ_DECKSHUFFLE,REASON_RULE)
	Duel.SendtoDeck(deck,nil,0,REASON_RULE)	end
	local g=Duel.GetDecktopGroup(tp,4)
	if #g<4 then return end
	Duel.ConfirmCards(tp,g)
	local sg1=g:RandomSelect(tp,1)
	Duel.Remove(sg1,POS_FACEDOWN,REASON_EFFECT)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetCode(EFFECT_ADD_SETCODE)
	e1:SetRange(LOCATION_REMOVED)
	e1:SetReset(RESET_EVENT+RESET_TOHAND)
	e1:SetValue(0xa03)
	sg1:GetFirst():RegisterEffect(e1)
	g:Sub(sg1)
	local sg2=g:RandomSelect(tp,1)
	Duel.Remove(sg2,POS_FACEDOWN,REASON_EFFECT)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e2:SetCode(EFFECT_ADD_SETCODE)
	e2:SetRange(LOCATION_REMOVED)
	e2:SetReset(RESET_EVENT+RESET_TOHAND)
	e2:SetValue(0xa03)
	sg2:GetFirst():RegisterEffect(e2)
	g:Sub(sg2)
	local sg3=g:RandomSelect(tp,1)
	Duel.Remove(sg3,POS_FACEDOWN,REASON_EFFECT)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetCode(EFFECT_ADD_SETCODE)
	e3:SetRange(LOCATION_REMOVED)
	e3:SetReset(RESET_EVENT+RESET_TOHAND)
	e3:SetValue(0xa03)
	sg3:GetFirst():RegisterEffect(e3)
	g:Sub(sg3)
	local sg4=g:RandomSelect(tp,1)
	Duel.Remove(sg4,POS_FACEDOWN,REASON_EFFECT)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e4:SetCode(EFFECT_ADD_SETCODE)
	e4:SetRange(LOCATION_REMOVED)
	e4:SetReset(RESET_EVENT+RESET_TOHAND)
	e4:SetValue(0xa03)
	sg4:GetFirst():RegisterEffect(e4)
end