--Gacha's Duel is Kami Game
Gacha2={}

--유닛 유틸
function Gacha2.UnitCharacter(c)
	Gacha2.SummonUnit(c)
	Gacha2.BattleCounterUnit(c)
	Gacha2.UnitEff(c)
	Gacha2.SnipeUnit(c)
	Gacha2.SpecialUnit(c)
	Gacha2.HintUnit(c)
end

--등장 스크립트
function Gacha2.SummonUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_SPSUM_PARAM)
	e1:SetRange(LOCATION_HAND)
	e1:SetTargetRange(POS_FACEUP_ATTACK,0)
	e1:SetCondition(Gacha2.sumcon)
	e1:SetOperation(Gacha2.sumop)
	c:RegisterEffect(e1)
end
function Gacha2.summonfilter(c)
	return c:IsDefensePos()
end
function Gacha2.sumcon(e,c)
   if c==nil then return true end
    local tp=c:GetControler()
    return (Duel.CheckRemoveOverlayCard(tp,1,0,c:GetLevel(),REASON_COST)
	or Duel.IsExistingMatchingCard(Gacha2.summonfilter,tp,LOCATION_EMZONE,0,1,nil))
	and not c:IsCode(11050018)
end
function Gacha2.sumop(e,tp,eg,ep,ev,re,r,rp,c)
	local c=e:GetHandler()
	local ct=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_EXTRA,0,nil):GetFirst()
	if Duel.IsExistingMatchingCard(Gacha2.summonfilter,tp,LOCATION_EMZONE,0,1,nil) then return end
	local g=Duel.GetOverlayGroup(tp,1,0)
	local ag=g:Select(tp,c:GetLevel(),c:GetLevel(),nil)
	Duel.SendtoGrave(ag,REASON_RULE)
end

--1체방어
function Gacha2.BattleCounterUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e1:SetCode(EVENT_BATTLE_START)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(Gacha2.btcountercon)
	e1:SetTarget(Gacha2.btcountertg)
	e1:SetOperation(Gacha2.btcounterop)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e2:SetCode(EVENT_BATTLE_START)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCondition(Gacha2.btcountercon2)
	e2:SetTarget(Gacha2.btcountertg)
	e2:SetOperation(Gacha2.btcounterop2)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e3:SetCode(EVENT_BATTLE_START)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e3:SetCondition(Gacha2.btcountercon3)
	e3:SetOperation(Gacha2.btcounterop3)
	c:RegisterEffect(e3)
end
function Gacha2.btcountercon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return Duel.GetAttacker():IsControler(1-tp) and Duel.GetAttackTarget()==nil 
	and c:IsAttackPos() and not c:IsCode(11020008) and not c:IsSetCard(0xb03)
end
function Gacha2.btcountertg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
	Duel.SetChainLimit(aux.FALSE)
end
function Gacha2.btcounterop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	if c:IsDefensePos() then return end
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetValue(0xa06)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e1)
		Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
		e2:SetCode(EVENT_PRE_DAMAGE_CALCULATE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		e2:SetOperation(Gacha2.btcoutertgop)
		c:RegisterEffect(e2)
end
function Gacha2.btcoutertgop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.CalculateDamage(at,c)
end
function Gacha2.btcountercon2(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetAttacker():IsControler(1-tp) and e:GetHandler():IsAttackPos() and Duel.GetAttackTarget()~=nil
end
function Gacha2.btcounterfilter2(c)
	return c:IsAttackPos() and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE) and not c:IsSetCard(0xa11)
end
function Gacha2.btcounterop2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
		local g=Duel.SelectMatchingCard(tp,Gacha2.btcounterfilter2,tp,LOCATION_ONFIELD,0,0,1,c)
		tc=g:GetFirst()
		if #g==0 then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetValue(0xa06)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e1) end
		if #g==1 then 	
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_ADD_SETCODE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetValue(0xa05)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(tc)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_ADD_SETCODE)
		e3:SetRange(LOCATION_ONFIELD)
		e3:SetValue(0xa05)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		tc:RegisterEffect(e3)
		Duel.ChangePosition(tc,POS_FACEUP_DEFENSE)
		local def=tc:GetDefense()
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_UPDATE_DEFENSE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetValue(def)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(tc)
		e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e5:SetCode(EVENT_LEAVE_FIELD)
		e5:SetRange(LOCATION_ONFIELD)
		e5:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e5:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e5:SetCondition(Gacha2.btcounterdescon2)
		e5:SetOperation(Gacha2.btcounterdesop2)
		tc:RegisterEffect(e5)	end
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_FIELD)
		e6:SetRange(LOCATION_ONFIELD)
		e6:SetCode(EFFECT_CHANGE_DAMAGE)
		e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e6:SetTargetRange(1,0)
		e6:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e6:SetValue(0)
		c:RegisterEffect(e6)
end
function Gacha2.btcounterdesfilter2(c)
	return c:IsReason(REASON_BATTLE)
end
function Gacha2.btcounterdescon2(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(Gacha2.btcounterdesfilter2,1,nil)
end
function Gacha2.btcounterdesop2(e,tp,eg,ep,ev,re,r,rp)
	Duel.Destroy(e:GetHandler(),REASON_BATTLE)
end
function Gacha2.btcountercon3(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetAttacker():IsControler(1-tp) and e:GetHandler():IsDefensePos() and Duel.GetAttackTarget()~=nil
end
function Gacha2.btcounterop3(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCode(EFFECT_CHANGE_DAMAGE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_PHASE+PHASE_DAMAGE)
	e1:SetValue(0)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCode(EFFECT_ADD_SETCODE)
	e2:SetRange(LOCATION_ONFIELD)
	e2:SetValue(0xa06)
	e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
	c:RegisterEffect(e2)
end

--유희왕과 다른 룰(1무한공격,2표시형식변경불가,3~4통상소환불가,6직공가능,7전투뎀1,8펜듈럼이아닌펜듈럼,9관통뎀)
function Gacha2.UnitEff(c)
	local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
    e1:SetCode(EFFECT_EXTRA_ATTACK)
    e1:SetValue(100)
    c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCode(EFFECT_CANNOT_CHANGE_POSITION)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e3:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_CANNOT_MSET)
	c:RegisterEffect(e4)
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetCode(EFFECT_DIRECT_ATTACK)
	e6:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	c:RegisterEffect(e6)
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e7:SetCode(EFFECT_CHANGE_BATTLE_DAMAGE)
	e7:SetValue(1)
	c:RegisterEffect(e7)
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e8:SetCode(EVENT_LEAVE_FIELD)
	e8:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e8:SetCondition(Gacha2.pencon)
	e8:SetOperation(Gacha2.penop)
	c:RegisterEffect(e8)
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_SINGLE)
	e9:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e9:SetCode(EFFECT_PIERCE)
	c:RegisterEffect(e9)
end
function Gacha2.pencon(e)
	return e:GetHandler():IsLocation(LOCATION_EXTRA)
end
function Gacha2.penop(e,tp,eg,ep,ev,re,r,rp)
	Duel.SendtoGrave(e:GetHandler(),REASON_EFFECT)
end

--0도발의시초,1사리엘,2제로저격,3쿠쿠저격
function Gacha2.SnipeUnit(c)
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e0:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
	e0:SetCondition(Gacha2.tgcon)
	e0:SetValue(Gacha2.tgfilter)
	c:RegisterEffect(e0)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
	e1:SetCondition(Gacha2.tgcon1)
	e1:SetValue(Gacha2.tgfilter1)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
	e2:SetCondition(Gacha2.tgcon2)
	e2:SetValue(Gacha2.tgfilter2)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e3:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
	e3:SetCondition(Gacha2.tgcon3)
	e3:SetValue(Gacha2.tgfilter3)
	c:RegisterEffect(e3)
end
function Gacha2.tgfilter(e,c)
	return c:IsAttackPos()
end
function Gacha2.tgcon(e)
	local c=e:GetHandler()
	return not c:IsSetCard(0xa02) and not c:IsSetCard(0xa07) and not c:IsSetCard(0xa08) and not c:IsSetCard(0xa13)
end
function Gacha2.tgfilter1(e,c)
	return not c:IsSetCard(0xb04)
end
function Gacha2.tgcon1(e)
	return e:GetHandler():IsSetCard(0xa07)
end
function Gacha2.tgfilter2(e,c)
	return not c:IsLevelBelow(4)
end
function Gacha2.tgcon2(e)
	return e:GetHandler():IsSetCard(0xa08)
end
function Gacha2.tgfilter3(e,c)
	return not c:IsLevelBelow(2)
end
function Gacha2.tgcon3(e)
	return e:GetHandler():IsSetCard(0xa13)
end

--1별자리
function Gacha2.CelestialUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_TOHAND)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_PHASE+PHASE_END)
	e1:SetProperty(EFFECT_FLAG_REPEAT)
	e1:SetCountLimit(1)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(Gacha2.Celestialcon)
	e1:SetOperation(Gacha2.Celestialop)
	c:RegisterEffect(e1)
end
function Gacha2.Celestialcon(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetTurnPlayer()==1-tp and e:GetHandler():IsDefensePos()
end
function Gacha2.Celestialop(e,tp,eg,ep,ev,re,r,rp)
	Duel.SendtoHand(e:GetHandler(),nil,REASON_EFFECT)
	Duel.ConfirmCards(1-tp,e:GetHandler())
end

--인스펙시온조건,1.1체공격불가,2협공+1체공격불가
function Gacha2.SpecialUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_CANNOT_ATTACK)
	e1:SetCondition(Gacha2.noonlyatkcon)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_CANNOT_ATTACK)
	e2:SetCondition(Gacha2.noonlyatkcon2)
	c:RegisterEffect(e2)
end
function Gacha2.noeffectcondition(e,tp,eg,ep,ev,re,r,rp)
	return not re:GetHandler():IsCode(11050010) and not re:GetHandler():IsCode(11050012)
end
function Gacha2.noonlyatkfllter(c)
    return c:IsPosition(POS_FACEUP_ATTACK) and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE)
	and not c:IsSetCard(0xa01)
end
function Gacha2.noonlyatkcon(e,c)
	local tp=e:GetHandlerPlayer()
    return Duel.GetMatchingGroupCount(Gacha2.noonlyatkfllter,tp,LOCATION_ONFIELD,0,e:GetHandler())==0
	and e:GetHandler():IsSetCard(0xa12)
end
function Gacha2.noonlyatkcon2(e,c)
	local tp=e:GetHandlerPlayer()
    return e:GetHandler():IsSetCard(0xa12) and e:GetHandler():IsSetCard(0xa01)
end


--1수비표시,2한정상태,3도발
function Gacha2.HintUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCode(EVENT_ADJUST)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(Gacha2.hintcon)
	e1:SetOperation(Gacha2.hintop)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCondition(Gacha2.hintcon2)
	e2:SetOperation(Gacha2.hintop2)
	c:RegisterEffect(e2)
	local e3=e1:Clone()
	e3:SetCondition(Gacha2.hintcon3)
	e3:SetOperation(Gacha2.hintop3)
	c:RegisterEffect(e3)
end
function Gacha2.hintcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsLocation(LOCATION_SZONE) and c:IsDefensePos()
end
function Gacha2.hintop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(11000001,0))
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CLIENT_HINT+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
	c:RegisterEffect(e1)
end
function Gacha2.hintcon2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsSetCard(0xb04)
end
function Gacha2.hintop2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(11000002,0))
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CLIENT_HINT+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	c:RegisterEffect(e1)
end
function Gacha2.hintcon3(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return Duel.IsTurnPlayer(1-tp) and c:IsSetCard(0xb05) and c:IsDefensePos()
end
function Gacha2.hintop3(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_MUST_ATTACK_MONSTER)
	e1:SetTargetRange(0,LOCATION_ONFIELD)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(Gacha2.dobalcon)
	e1:SetTarget(Gacha2.filter)
	e1:SetValue(aux.TargetBoolFunction(Gacha2.dobalop))
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(11020008,0))
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_CLIENT_HINT+EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCondition(Gacha2.dobalcon)
	e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
	c:RegisterEffect(e2)
end
function Gacha2.dobalcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsSetCard(0xb05) and c:IsDefensePos()
end
function Gacha2.filter(e,c)
	return not c:IsSetCard(0xb06)
end
function Gacha2.dobalop(c)
	return c:IsDefensePos()
end